#!/bin/bash
echo "enter name of file"
read "filename"
cp "$filename" temp
cd temp
echo "what is the current name desired"
read "currentname"
mv "$filename" "$currentname"
mv "$currentname" /home/victortech/ALX/alx-higher_level_programming/0x06-python-classes
